Repository codestates-seb/seb44_main_016, pull requests merged in 2023-09, with the labels that each got.

#330 fix: 사용자별 가계부 전체조회를 위한 쿼리문 수정
  server/src/main/java/com/zerohip/server/financialRecord/repository/FinancialRecordRepository.java
Labels: 🐛 FIX, 🐶 BE

#331 fix: 사용자별 가계부 전체조회를 위한 쿼리문 수정
  server/src/main/java/com/zerohip/server/financialRecord/repository/FinancialRecordRepository.java
Labels: 🐶 BE

#334 [FE] 구글 정책에 맞춘 디자인 변경 및 로그인 검증 함수 등 리팩토링
  client/public/images/icon/oauth/google.svg
  client/public/images/icon/oauth/kakao.svg
  client/public/images/icon/oauth/naver.svg
  client/src/components/Aside.tsx
  client/src/components/WithAuth.tsx
  client/src/components/auth/WithAuth.tsx
  client/src/components/auth/getAccessByRefresh.ts
  client/src/pages/editor/index.tsx
  client/src/pages/financialrecord/create/index.tsx
  client/src/pages/financialrecord/edit/[slug]/index.tsx
  client/src/pages/financialrecord/index.tsx
  client/src/pages/financialrecord/index2.tsx
  client/src/pages/financialrecord/list/[slug]/index.tsx
  client/src/pages/user/delete/goodbye/index.tsx
  client/src/pages/user/delete/index.tsx
  client/src/pages/user/login/Google.tsx
  client/src/pages/user/login/Kakao.tsx
  client/src/pages/user/login/Naver.tsx
  client/src/pages/user/login/OAuth.tsx
  client/src/pages/user/mypage/index.tsx
  client/src/services/apiUser.ts
  client/src/services/tokenInstance.ts
  client/src/services/useMutateUser.ts
  client/src/utils/validationCheck.ts
  client/tailwind.config.js
  client/withTwin.js
Labels: 🐛 FIX, 🐱 FE

#333 [BE] User follow-332
  server/src/main/java/com/zerohip/server/common/exception/ExceptionCode.java
  server/src/main/java/com/zerohip/server/follow/controller/FollowController.java
  server/src/main/java/com/zerohip/server/follow/dto/FollowDto.java
  server/src/main/java/com/zerohip/server/follow/entity/Follow.java
  server/src/main/java/com/zerohip/server/follow/mapper/FollowMapper.java
  server/src/main/java/com/zerohip/server/follow/repository/FollowRepository.java
  server/src/main/java/com/zerohip/server/follow/service/FollowService.java
  server/src/main/java/com/zerohip/server/user/controller/UserController.java
  server/src/main/java/com/zerohip/server/user/dto/UserDto.java
  server/src/main/java/com/zerohip/server/user/entity/User.java
  server/src/main/java/com/zerohip/server/user/mapper/UserMapper.java
  server/src/main/java/com/zerohip/server/user/repository/UserRepository.java
  server/src/main/java/com/zerohip/server/user/service/UserService.java
  server/src/main/java/com/zerohip/server/user/service/UserServiceImpl.java
Labels: ✨ FEAT, 🐶 BE

#336 fix: 조회관련 기능 일부 수정
  server/src/main/java/com/zerohip/server/financialRecord/entity/FinancialRecord.java
  server/src/main/java/com/zerohip/server/financialRecord/repository/FinancialRecordRepository.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordServiceImpl.java
Labels: 🐛 FIX, 🐶 BE

#324 (작업 중) [BE] 투표기능 + 피드게시글 컨트롤러 수정
  server/src/main/java/com/zerohip/server/common/vote/controller/VoteController.java
  server/src/main/java/com/zerohip/server/common/vote/dto/VoteResponse.java
  server/src/main/java/com/zerohip/server/common/vote/entity/Vote.java
  server/src/main/java/com/zerohip/server/common/vote/repository/VoteRepository.java
  server/src/main/java/com/zerohip/server/common/vote/service/VoteService.java
  server/src/main/java/com/zerohip/server/common/vote/service/VoteServiceImpl.java
  server/src/main/java/com/zerohip/server/common/voteType/VoteType.java
  server/src/main/java/com/zerohip/server/feedArticle/controller/FeedArticleController.java
Labels: 🐛 FIX, 🧹 CHORE, 🐶 BE

#339 [FE] 공통 컴포넌트 및 함수 추출 외 리팩토링
  client/next.config.js
  client/src/components/aside/AsideHamburgerBtn.tsx
  client/src/components/auth/WithAuth.tsx
  client/src/components/home-header/ProfileHamburgerBtn.tsx
  client/src/components/redux/getUserInfo.tsx
  client/src/components/userpage/FollowModal.tsx
  client/src/constants/oauth/oauth.ts
  client/src/hooks/useComponents.tsx
  client/src/hooks/useScreenSizeWithMount.ts
  client/src/pages/oauth/google/index.tsx
  client/src/pages/oauth/kakao/index.tsx
  client/src/pages/oauth/naver/index.tsx
  client/src/pages/user/delete/index.tsx
  client/src/pages/user/login/Google.tsx
  client/src/pages/user/login/Kakao.tsx
  client/src/pages/user/login/LoginFormBox.tsx
  client/src/pages/user/login/Naver.tsx
  client/src/pages/user/login/OAuth.tsx
  client/src/pages/user/login/OAuthBtn.tsx
  client/src/pages/user/login/index.tsx
  client/src/pages/user/mypage/FollowList.tsx
  client/src/pages/user/mypage/MyPageUserInfo.tsx
  client/src/pages/user/signup/SignUpForm.tsx
  client/src/pages/user/signup/SignUpInputField.tsx
  client/src/pages/user/signup/index.tsx
  client/src/pages/user/update/ProfileImgUpdate.tsx
  client/src/pages/user/update/RandomAvatarUpdate.tsx
  client/src/pages/user/update/UserImgFileUpdate.tsx
  client/src/pages/user/update/UserInputField.tsx
  client/src/pages/user/update/UserUpdatePage.tsx
  client/src/services/apiFinancial.ts
  client/src/services/apiSns.ts
  client/src/services/apiUser.ts
  client/src/services/axios-instance/tokenInstance.ts
  client/src/services/mutate/useMutateUser.ts
  client/src/types/user.ts
  client/src/utils/common/getInputData.tsx
  client/src/utils/common/validation/inputValidationError.ts
  client/src/utils/common/validation/isValidForm.ts
  client/src/utils/common/validation/validationCheck.ts
  client/src/utils/oauth/getOAuthComponent.tsx
  client/src/utils/oauth/handleOAuthLogin.ts
  client/src/utils/userpage/currentImageRender.tsx
Labels: 🐛 FIX, 🐱 FE

#337 [BE] 유저 프로필 및 북마크 추가/제거
  server/src/main/java/com/zerohip/server/common/img/entity/Img.java
  server/src/main/java/com/zerohip/server/common/img/service/ImgService.java
  server/src/main/java/com/zerohip/server/common/img/service/ImgServiceImpl.java
  server/src/main/java/com/zerohip/server/common/img/service/S3ImgServiceImpl.java
  server/src/main/java/com/zerohip/server/financialRecord/controller/FinancialRecordController.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordService.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordServiceImpl.java
  server/src/main/java/com/zerohip/server/user/entity/User.java
Labels: 🐶 BE

#341 [BE] 프로필이미지 삭제 시 랜덤이미지로 변경하기
  server/src/main/java/com/zerohip/server/common/img/service/ImgService.java
  server/src/main/java/com/zerohip/server/common/img/service/S3ImgServiceImpl.java
  server/src/main/java/com/zerohip/server/user/entity/User.java
Labels: ✨ FEAT, 🐶 BE

#342 [BE] fix: ImgServiceImpl 주석처리
  server/src/main/java/com/zerohip/server/common/img/service/ImgService.java
  server/src/main/java/com/zerohip/server/common/img/service/ImgServiceImpl.java
  server/src/main/java/com/zerohip/server/common/img/service/S3ImgServiceImpl.java
Labels: 🐛 FIX, 🐶 BE

#343 [FE] 구독 기능 구현
  client/src/components/userpage/FollowList.tsx
  client/src/components/userpage/FollowModal.tsx
  client/src/components/userpage/UserPageInfo.tsx
  client/src/hooks/interface/useBetterUXWithEscapeBtn.ts
  client/src/hooks/userpage/index.ts
  client/src/hooks/userpage/useCheckIsMyPageFirst.ts
  client/src/hooks/userpage/useFollowMutation.ts
  client/src/hooks/userpage/useFollowStatus.ts
  client/src/pages/api/financial-record/[slug]/article/index.ts
  client/src/pages/api/financial-record/[slug]/index.ts
  client/src/pages/api/financial-record/index.ts
  client/src/pages/api/user/[slug]/feedArticles/index.ts
  client/src/pages/api/user/delete/index.ts
  client/src/pages/api/user/login/index.ts
  client/src/pages/api/user/logout/index.ts
  client/src/pages/api/user/mypage/index.ts
  client/src/pages/api/user/signup/index.ts
  client/src/pages/api/user/update/index.ts
  client/src/pages/user/mypage/index.tsx
  client/src/pages/user/profile/[loginId]/index.tsx
  client/src/services/apiUser.ts
  client/src/services/mutate/useMutateUser.ts
  client/src/types/user.ts
  client/src/utils/userpage/getFollowStatus.ts
Labels: 🐱 FE, ✨ FEAT

#344 [FE] 유저 페이지 SEO 개선 (SSR로 동적 meta 태그 생성 외)
  client/src/components/HeadMeta.tsx
  client/src/components/userpage/UserPageInfo.tsx
  client/src/constants/oauth/oauth.ts
  client/src/constants/seo/userMetaData.ts
  client/src/hooks/userpage/useCheckIsMyPageFirst.ts
  client/src/hooks/userpage/useFollowStatus.ts
  client/src/pages/_app.tsx
  client/src/pages/_document.tsx
  client/src/pages/user/mypage/index.tsx
  client/src/pages/user/profile/[userId]/index.tsx
  client/src/services/apiUser.ts
  client/src/types/user.ts
Labels: 🐱 FE, ✨ FEAT
