Repository codestates-seb/seb44_main_016, pull requests merged in 2023-07, with the labels that each got.

#36 design: 최상위 컴포넌트 너비 지정
  client/src/components/common/PageTemplate.tsx
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/src/pages/test/index.tsx
  client/src/styles/GlobalStyles.tsx
Labels: 🐱 FE, 🖌️ UI

#53 design & feat: 게시글 편집 페이지(editor) 구현
  client/package-lock.json
  client/package.json
  client/src/components/common/PageTemplate.tsx
  client/src/pages/editor/index.tsx
  client/src/pages/index.tsx
Labels: 🐱 FE, ✨ FEAT, 🖌️ UI

#59 [FE] style-7 : 공통 스타일 지정 및 input design
  client/src/styles/CommonStyles.tsx
  client/src/styles/GlobalStyles.tsx
  client/tailwind.config.js
Labels: 🐱 FE, 🖌️ UI

#61 [FE] style : style branch merge
  client/src/styles/CommonStyles.tsx
  client/src/styles/GlobalStyles.tsx
  client/tailwind.config.js
Labels: 🐱 FE, 🖌️ UI

#64 feat: Add 가계부 조회확인
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordService.java
Labels: ✨ FEAT, 🐶 BE

#68 [FE] style-65 feat : 공통 레이아웃 설정
  client/src/components/common/PageTemplate.tsx
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/src/pages/test/test1/index.tsx
Labels: 🐱 FE, 🖌️ UI

#66 fix: 전체 조회 및 수정 인터페이스 수정
  server/src/main/java/com/zerohip/server/feedArticle/service/FeedArticleService.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordService.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleService.java
  server/src/main/java/com/zerohip/server/user/service/UserService.java
Labels: ✨ FEAT, 🐶 BE

#71 Fa rec - 인터페이스 수정 pull을 위해 trunk에 merge
  server/.idea/.gitignore
  server/.idea/discord.xml
  server/src/main/java/com/zerohip/server/feedArticle/service/FeedArticleService.java
  server/src/main/java/com/zerohip/server/financialRecord/entity/FinancialRecord.java
  server/src/main/java/com/zerohip/server/financialRecord/repository/FinancialRecordRepository.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordService.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleService.java
  server/src/main/java/com/zerohip/server/user/service/UserService.java
Labels: ✨ FEAT, 🐶 BE

#67 Fa rec 42
  server/build.gradle
  server/src/main/java/com/zerohip/server/feedArticle/repository/FeedArticleRepository.java
  server/src/main/java/com/zerohip/server/financialRecord/dto/FinancialRecordDto.java
  server/src/main/java/com/zerohip/server/financialRecord/entity/FinancialRecord.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordService.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordServiceImpl.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/repository/FinancialRecordArticleRepository.java
  server/src/main/java/com/zerohip/server/user/repository/UserRepository.java
  server/src/test/java/com/zerohip/server/financialRecord/repository/FinancialRecordRepositoryTest.java
  server/src/test/java/com/zerohip/server/financialRecord/service/FinancialRecordServiceImplTest.java
Labels: ✨ FEAT, 🐶 BE

#69 [FE] design: 게시글 편집 페이지에 CommonStyles 적용
  client/src/components/common/PageTemplate.tsx
  client/src/pages/_app.tsx
  client/src/pages/editor/index.tsx
  client/src/pages/index.tsx
  client/src/pages/test/test1/index.tsx
Labels: 🐱 FE, 🖌️ UI

#72 [FE] article-11: <SnsArticle> 더미 데이터 객체를 이용한 디자인 구현
  client/src/components/common/SnsArticle.tsx
  client/src/components/common/snsarticle/Comment.tsx
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
Labels: 🐱 FE, ✨ FEAT, 🖌️ UI

#78 [FE] User-29 : 회원가입 화면 UI
  client/custom.d.ts
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/public/logo.svg
  client/src/components/common/PageTemplate.tsx
  client/src/constants/signUp.ts
  client/src/hooks/useInput.tsx
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/src/pages/test/test1/index.tsx
  client/src/pages/user/signup/SignUpForm.tsx
  client/src/pages/user/signup/index.tsx
  client/src/styles/CommonStyles.tsx
  client/src/styles/GlobalStyles.tsx
  client/tailwind.config.js
  client/tsconfig.json
Labels: 🐱 FE, 🖌️ UI

#54 feat : 해시태그 인터페이스
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/server.main.iml
  .idea/vcs.xml
  .idea/workspace.xml
  server/.gradle/8.1.1/executionHistory/executionHistory.bin
  server/.gradle/8.1.1/executionHistory/executionHistory.lock
  server/.gradle/8.1.1/fileHashes/fileHashes.bin
  server/.gradle/8.1.1/fileHashes/fileHashes.lock
  server/.gradle/8.1.1/fileHashes/resourceHashesCache.bin
  server/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  server/.gradle/buildOutputCleanup/outputFiles.bin
  server/.gradle/file-system.probe
  server/build/classes/java/main/com/zerohip/server/ServerApplication.class
  server/build/classes/java/main/com/zerohip/server/common/audit/Auditable.class
  server/build/classes/java/main/com/zerohip/server/common/service/HashtagService.class
  server/build/classes/java/main/com/zerohip/server/feedArticle/entity/FeedArticle.class
  server/build/classes/java/main/com/zerohip/server/feedArticle/repository/FeedArticleRepository.class
  server/build/classes/java/main/com/zerohip/server/feedArticle/service/FeedArticleService.class
  server/build/classes/java/main/com/zerohip/server/financialRecord/entity/FinancialRecord.class
  server/build/classes/java/main/com/zerohip/server/financialRecord/repository/FinancialRecordRepository.class
  server/build/classes/java/main/com/zerohip/server/financialRecord/service/FinancialRecordService.class
  server/build/classes/java/main/com/zerohip/server/financialRecordArticle/entity/FinancialRecordArticle.class
  server/build/classes/java/main/com/zerohip/server/financialRecordArticle/repository/FinancialRecordArticleRepository.class
  server/build/classes/java/main/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleService.class
  server/build/classes/java/main/com/zerohip/server/user/entity/User.class
  server/build/classes/java/main/com/zerohip/server/user/repository/UserRepository.class
  server/build/classes/java/main/com/zerohip/server/user/service/UserService.class
  server/build/resources/main/application-local.yml
  server/build/resources/main/application-prod.yml
  server/build/resources/main/application.yml
  server/build/tmp/compileJava/previous-compilation-data.bin
  server/src/main/java/com/zerohip/server/common/entity/Hashtag.java
  server/src/main/java/com/zerohip/server/common/repository/HashtagRepository.java
  server/src/main/java/com/zerohip/server/common/service/HashtagService.java
Labels: ✨ FEAT, 🐶 BE

#81 [FE] Style-80 tailwind-css에서 emotion-css로 변경
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/src/styles/CommonStyles.tsx
  client/src/styles/GlobalStyles.tsx
Labels: 🐛 FIX, 🐱 FE, 🖌️ UI

#82 [FE] faRec - 8 가계부 리스트 UI
  client/custom.d.ts
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/public/bookmark.svg
  client/public/images/icon/search.svg
  client/src/components/common/PageTemplate.tsx
  client/src/constants/pageNames.ts
  client/src/pages/_app.tsx
  client/src/pages/financialrecord/list/ListItem.tsx
  client/src/pages/financialrecord/list/index.tsx
  client/src/pages/index.tsx
  client/src/pages/test/test1/index.tsx
  client/src/styles/CommonStyles.tsx
  client/src/styles/GlobalStyles.tsx
  client/tailwind.config.js
  client/tsconfig.json
Labels: 🐱 FE, 🖌️ UI

#84 [FE] tanstackQuery-83 tanstack-query 설정
  client/package-lock.json
  client/package.json
  client/src/pages/_app.tsx
Labels: 🐱 FE, ✨ FEAT

#86 [FE] article-73: <SnsArticle> 더미 데이터 객체를 이용한 타임라인 게시글 디자인 구현
  client/package-lock.json
  client/package.json
  client/src/components/common/SnsArticle.tsx
  client/src/components/common/snsarticle/ArticleHeader.tsx
  client/src/components/common/snsarticle/Comment.tsx
  client/src/components/common/snsarticle/Comments.tsx
  client/src/components/common/snsarticle/VoteForm.tsx
  client/src/components/common/snsarticle/comments/Comment.tsx
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/src/styles/CommonStyles.tsx
  client/src/styles/GlobalStyles.tsx
  server/.idea/.gitignore
  server/.idea/discord.xml
  server/src/main/java/com/zerohip/server/feedArticle/service/FeedArticleService.java
  server/src/main/java/com/zerohip/server/financialRecord/entity/FinancialRecord.java
  server/src/main/java/com/zerohip/server/financialRecord/repository/FinancialRecordRepository.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordService.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleService.java
  server/src/main/java/com/zerohip/server/user/service/UserService.java
Labels: 🐱 FE, ✨ FEAT, 🖌️ UI

#87 [FE] Hotfix: 불필요한 X축 스크롤바 버그 수정
  client/src/pages/_app.tsx
Labels: 🐛 FIX, 🐱 FE

#88 [BE] 피드 게시글 생성 관련 dto, service, entity
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/server.main.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/workspace.xml
  client/src/components/common/snsarticle/Comment.tsx
  server/.gradle/8.1.1/checksums/checksums.lock
  server/.gradle/8.1.1/checksums/md5-checksums.bin
  server/.gradle/8.1.1/checksums/sha1-checksums.bin
  server/build.gradle
  server/src/main/java/com/zerohip/server/common/feedType/FeedType.java
  server/src/main/java/com/zerohip/server/feedArticle/dto/FeedArticleDto.java
  server/src/main/java/com/zerohip/server/feedArticle/entity/FeedArticle.java
  server/src/main/java/com/zerohip/server/feedArticle/service/FeedArticleService.java
  server/src/main/java/com/zerohip/server/feedArticle/service/FeedArticleServiceImpl.java
  server/src/main/java/com/zerohip/server/financialRecord/repository/FinancialRecordRepository.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordService.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/repository/FinancialRecordArticleRepository.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleService.java
  server/src/main/java/com/zerohip/server/user/repository/UserRepository.java
Labels: ✨ FEAT, 🐶 BE

#93 [FE] Reusable-92 : 재사용 가능한 input, checkout 박스 생성
  client/src/hooks/useComponents.tsx
  client/src/pages/test/index.tsx
  client/src/pages/test/test1/index.tsx
  client/types/twin.d.ts
Labels: 🐱 FE, ✨ FEAT

#91 [FE] faRec-9 가계부 목록 페이지 기능
  client/package-lock.json
  client/package.json
  client/public/data/recordList.json
  client/public/images/icon/bookmark.svg
  client/src/pages/_app.tsx
  client/src/pages/financial-record/ListItem.tsx
  client/src/pages/financial-record/financial-list/[slug]/RecordHeader.tsx
  client/src/pages/financial-record/financial-list/[slug]/index.tsx
  client/src/pages/financial-record/financial-list/[slug]/layout.tsx
  client/src/pages/financial-record/financial-list/[slug]/timeline.tsx
  client/src/pages/financial-record/index.tsx
  client/src/pages/financialrecord/list/index.tsx
  client/src/services/financialAPI.ts
Labels: 🐱 FE, ✨ FEAT

#95 [Fe] User-55 : 회원가입 C 기능 구현
  client/package-lock.json
  client/package.json
  client/public/image/dropdown.svg
  client/public/image/logo.svg
  client/src/components/SelectBox.tsx
  client/src/constants/signUp.ts
  client/src/hooks/useComponents.tsx
  client/src/hooks/useInput.tsx
  client/src/pages/_app.tsx
  client/src/pages/api/user/signup/index.ts
  client/src/pages/index.tsx
  client/src/pages/test/index.tsx
  client/src/pages/test/test1/index.tsx
  client/src/pages/test/userData.ts
  client/src/pages/user/signup/SignUpForm.tsx
  client/src/pages/user/signup/index.tsx
  client/src/services/apiRequest.ts
  client/src/styles/CommonStyles.tsx
  client/src/styles/GlobalStyles.tsx
  client/src/types/SignUp.ts
  client/src/utils/validationCheck.ts
  client/types/twin.d.ts
  server/.idea/.gitignore
  server/.idea/discord.xml
  server/src/main/java/com/zerohip/server/feedArticle/service/FeedArticleService.java
  server/src/main/java/com/zerohip/server/financialRecord/entity/FinancialRecord.java
  server/src/main/java/com/zerohip/server/financialRecord/repository/FinancialRecordRepository.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordService.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleService.java
  server/src/main/java/com/zerohip/server/user/service/UserService.java
Labels: 🐱 FE, ✨ FEAT

#96 [FE] Aside-14: `<Aside>` UI & 기능
  client/src/components/Aside.tsx
  client/src/components/aside/AsideButton.tsx
  client/src/components/aside/SvgBox.tsx
  client/src/constants/svg.tsx
  client/src/pages/_app.tsx
Labels: 🐱 FE, ✨ FEAT, 🖌️ UI

#99 [FE] `<Aside>` 및 `<Component {...pageProps}>` 버그 수정
  client/src/components/Aside.tsx
  client/src/pages/_app.tsx
Labels: 🐛 FIX, 🐱 FE, 🖌️ UI

#102 [BE]피드 게시글 및 피드 조회
  server/src/main/java/com/zerohip/server/feedArticle/dto/FeedArticleDto.java
  server/src/main/java/com/zerohip/server/feedArticle/entity/FeedArticle.java
  server/src/main/java/com/zerohip/server/feedArticle/service/FeedArticleService.java
  server/src/main/java/com/zerohip/server/feedArticle/service/FeedArticleServiceImpl.java
Labels: ✨ FEAT, 🐶 BE

#103 [FE] Homeheader-16: `<HomeHeader>` UI
  client/src/components/Aside.tsx
  client/src/components/HomeHeader.tsx
  client/src/pages/_app.tsx
Labels: 🐱 FE, 🖌️ UI

#101 [FE] FaRec-10 가계부 생성UI 10
  client/public/images/icon/plus.svg
  client/src/components/Aside.tsx
  client/src/components/aside/AsideButton.tsx
  client/src/components/aside/SvgBox.tsx
  client/src/constants/svg.tsx
  client/src/hooks/useComponents.tsx
  client/src/pages/_app.tsx
  client/src/pages/api/financial-record/index.ts
  client/src/pages/financial-record/FaRecForm.tsx
  client/src/pages/financial-record/create/index.tsx
  client/src/pages/financial-record/index.tsx
  client/src/pages/test/index.tsx
  client/src/pages/test/recordList.ts
  client/src/pages/test/test1/index.tsx
  client/src/services/apiFinancial.ts
  client/types/twin.d.ts
Labels: 🐱 FE, ✨ FEAT, 🖌️ UI

#116 [FE] User 97 : 회원 RUD (마이페이지, 회원정보 수정, 회원 탈퇴) UI 완성
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/public/image/back2.svg
  client/public/image/closeBtn.svg
  client/public/image/imageUpload.svg
  client/public/image/mango.png
  client/public/image/mango2.png
  client/src/animation/delete.json
  client/src/animation/loading.json
  client/src/components/Aside.tsx
  client/src/components/CheckboxAgreement.tsx
  client/src/components/HomeHeader.tsx
  client/src/components/Loading.tsx
  client/src/components/SelectBox.tsx
  client/src/components/aside/AsideButton.tsx
  client/src/components/aside/SvgBox.tsx
  client/src/constants/signUp.ts
  client/src/constants/svg.tsx
  client/src/constants/user.ts
  client/src/hooks/useComponents.tsx
  client/src/pages/_app.tsx
  client/src/pages/user/delete/goodbye/index.tsx
  client/src/pages/user/delete/index.tsx
  client/src/pages/user/mypage/[slug]/FollowList.tsx
  client/src/pages/user/mypage/[slug]/FollowModal.tsx
  client/src/pages/user/mypage/[slug]/index.tsx
  client/src/pages/user/signup/SignUpForm.tsx
  client/src/pages/user/signup/index.tsx
  client/src/pages/user/update/index.tsx
  client/src/services/apiUser.ts
  client/src/styles/GlobalStyles.tsx
  client/src/types/user.ts
  client/src/utils/validationCheck.ts
Labels: 🐱 FE, 🖌️ UI

#115 [FE] designsemantic-109: `<HomeHeader>`, `<Aside>` 디자인/시맨틱 개선
  client/src/components/Aside.tsx
  client/src/components/HomeHeader.tsx
  client/src/components/aside/AsideButton.tsx
  client/src/components/aside/AsideLogo.tsx
  client/src/components/aside/AsideProfileBox.tsx
  client/src/components/aside/SvgBox.tsx
  client/src/pages/_app.tsx
  client/src/styles/GlobalStyles.tsx
Labels: 🐱 FE, 🖌️ UI

#118 [FE] ImgCrop-104 : img crop component & hook
  client/package-lock.json
  client/package.json
  client/src/components/img-crop/ImgCropModal.tsx
  client/src/components/img-crop/canvasUtils.ts
  client/src/components/img-crop/imgCropUtils.ts
  client/src/hooks/useImgCrop.tsx
  client/src/pages/crop-test/index.tsx
Labels: 🐱 FE, ✨ FEAT

#124 [FE] User 117 : 로그인 페이지 UI 및 HeadingsMap을 이용한 웹 접근성 개선 (코드리뷰 반영)
  client/package-lock.json
  client/public/icon/google.svg
  client/public/icon/kakao.svg
  client/public/icon/naver.svg
  client/src/animation/keyframe.ts
  client/src/components/CheckboxAgreement.tsx
  client/src/pages/_app.tsx
  client/src/pages/user/delete/goodbye/index.tsx
  client/src/pages/user/delete/index.tsx
  client/src/pages/user/login/OAuth.tsx
  client/src/pages/user/login/index.tsx
  client/src/pages/user/mypage/[slug]/FollowList.tsx
  client/src/pages/user/mypage/[slug]/FollowModal.tsx
  client/src/pages/user/mypage/[slug]/index.tsx
  client/src/pages/user/signup/SignUpForm.tsx
  client/src/pages/user/signup/index.tsx
  client/src/pages/user/update/index.tsx
  client/src/styles/GlobalStyles.tsx
Labels: 🐱 FE, 🖌️ UI

#122 [FE] blind-121 : feat :visual hidden css 추가
  client/src/styles/GlobalStyles.tsx
Labels: 🐱 FE, ✨ FEAT, 🖌️ UI

#127 [FE] Editor-85: 게시글 편집 페이지 tw → styled & 디자인/시맨틱 개선
  client/package-lock.json
  client/src/pages/editor/ImgBox.tsx
  client/src/pages/editor/ImgsUploader.tsx
  client/src/pages/editor/InputNaturalNumber.tsx
  client/src/pages/editor/RadioSet.tsx
  client/src/pages/editor/SelectOption.tsx
  client/src/pages/editor/StyledDatePicker.tsx
  client/src/pages/editor/index.tsx
  client/src/styles/GlobalStyles.tsx
Labels: 🐱 FE, ✨ FEAT, 🖌️ UI

#106 [BE] Feat: 가계부 게시글 관련 유효성 검증 추가
  server/build/generated/sources/annotationProcessor/java/main/com/zerohip/server/financialRecord/mapper/FinancialRecordMapperImpl.java
  server/src/main/java/com/zerohip/server/common/scope/Scope.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/dto/FinancialRecordArticleDto.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/entity/FinancialRecordArticle.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleService.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleServiceImpl.java
  server/src/test/java/com/zerohip/server/financialRecordArticle/repository/FinancialRecordArticleRepositoryTest.java
Labels: ✨ FEAT, 🐶 BE

#120 [BE] 피드 게시글 조회 및 전체 피드 조회
  server/src/main/java/com/zerohip/server/feedArticle/dto/FeedArticleDto.java
  server/src/main/java/com/zerohip/server/feedArticle/service/FeedArticleService.java
  server/src/main/java/com/zerohip/server/feedArticle/service/FeedArticleServiceImpl.java
  server/src/main/java/com/zerohip/server/user/service/UserService.java
Labels: ✨ FEAT, 🐶 BE

#134 [BE] Fa rec 개발자 테스트를 위한 데이터 통합
  client/package-lock.json
  client/package.json
  client/src/components/Aside.tsx
  client/src/components/HomeHeader.tsx
  client/src/components/aside/AsideButton.tsx
  client/src/components/aside/AsideLogo.tsx
  client/src/components/aside/AsideProfileBox.tsx
  client/src/components/aside/SvgBox.tsx
  client/src/components/common/PageTemplate.tsx
  client/src/components/img-crop/ImgCropModal.tsx
  client/src/components/img-crop/canvasUtils.ts
  client/src/components/img-crop/imgCropUtils.ts
  client/src/constants/svg.tsx
  client/src/hooks/useComponents.tsx
  client/src/hooks/useImgCrop.tsx
  client/src/pages/_app.tsx
  client/src/pages/crop-test/index.tsx
  client/src/pages/index.tsx
  client/src/pages/test/index.tsx
  client/src/styles/CommonStyles.tsx
  client/src/styles/GlobalStyles.tsx
  client/tailwind.config.js
  client/types/twin.d.ts
Labels: 🐶 BE

#145 User-144/be delete
  server/src/main/java/com/zerohip/server/user/controller/UserController.java
  server/src/main/java/com/zerohip/server/user/service/UserServiceImpl.java
Labels: ✨ FEAT, 🐶 BE

#149 User 144 be dependency update
  server/build.gradle
Labels: 🐛 FIX, 🐶 BE

#141 [FE] Label-140 : FilePlusLabel 컴포넌트 생성
  client/custom.d.ts
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/public/images/icon/plus.svg
  client/src/components/FilePlusLabel.tsx
  client/src/pages/crop-test/index.tsx
  client/tsconfig.json
Labels: 🐱 FE, 🖌️ UI

#130 [FE] faRec-15 : 가계부 생성 C, U
  client/package-lock.json
  client/public/images/icon/person.svg
  client/public/images/randomImg/randomImg0.jpeg
  client/public/images/randomImg/randomImg1.jpeg
  client/public/images/randomImg/randomImg2.jpeg
  client/public/images/randomImg/randomImg3.jpeg
  client/public/images/randomImg/randomImg4.jpeg
  client/public/images/randomImg/randomImg5.jpeg
  client/public/images/randomImg/randomImg6.jpeg
  client/public/images/randomImg/randomImg7.jpeg
  client/public/images/randomImg/randomImg8.jpeg
  client/public/images/randomImg/randomImg9.jpeg
  client/src/components/InputField.tsx
  client/src/constants/faRecImgUrls.ts
  client/src/pages/api/financial-record/[slug]/index.ts
  client/src/pages/api/financial-record/index.ts
  client/src/pages/financial-record/FaRecForm.tsx
  client/src/pages/financial-record/create/index.tsx
  client/src/pages/financial-record/edit/[slug]/index.tsx
  client/src/pages/test/recordList.ts
  client/src/services/apiFinancial.ts
  client/src/styles/GlobalStyles.tsx
  client/src/utils/randomImg.ts
Labels: 🐱 FE, ✨ FEAT

#143 [BE] 가계부 설명 필드 추가
  server/src/main/java/com/zerohip/server/feedArticle/service/FeedArticleService.java
  server/src/main/java/com/zerohip/server/financialRecord/controller/FinancialRecordController.java
  server/src/main/java/com/zerohip/server/financialRecord/dto/FinancialRecordDto.java
  server/src/main/java/com/zerohip/server/financialRecord/entity/FinancialRecord.java
  server/src/main/java/com/zerohip/server/financialRecord/mapper/FinancialRecordMapper.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordService.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordServiceImpl.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleService.java
  server/src/main/java/com/zerohip/server/user/service/UserService.java
  server/src/test/java/com/zerohip/server/financialRecord/repository/FinancialRecordRepositoryTest.java
  server/src/test/java/com/zerohip/server/financialRecord/service/FinancialRecordServiceImplTest.java
Labels: ✨ FEAT, 🐶 BE

#158 [FE] buttonStyle:-156 : Button style color props 추가 및 Link 태그 디자인 추가
  client/src/pages/crop-test/index.tsx
  client/src/styles/CommonStyles.tsx
  client/src/styles/GlobalStyles.tsx
Labels: 🐱 FE, 🖌️ UI

#164 [BE]feat: FeedArticleMapper 추가
  server/src/main/java/com/zerohip/server/feedArticle/mapper/FeedArticleMapper.java
Labels: ✨ FEAT, 🐶 BE

#152 [FE] Article-111: `<SnsArticle>` 디자인/시맨틱 개선
  client/src/components/Aside.tsx
  client/src/components/HomeHeader.tsx
  client/src/components/SnsArticle.tsx
  client/src/components/common/snsarticle/Comment.tsx
  client/src/components/sns-article/ArticleHeader.tsx
  client/src/components/sns-article/Comments.tsx
  client/src/components/sns-article/VoteForm.tsx
  client/src/components/sns-article/comments/Comment.tsx
  client/src/constants/svg.tsx
  client/src/hooks/useRangeNumber.ts
  client/src/pages/index.tsx
  client/src/styles/GlobalStyles.tsx
Labels: 🐱 FE, ✨ FEAT, 🖌️ UI

#166 [FE] [🔥Hotfix] buttonProps-165 : LinkBtn 컴포넌트 props type error 수정
  client/src/styles/CommonStyles.tsx
Labels: 🐛 FIX, 🐱 FE, 🖌️ UI

#169 [FE] Common-107: `<HomeHeader>`, `<Aside>` 디자인 개선 & 임시 라우팅 적용
  client/src/components/Aside.tsx
  client/src/components/HomeHeader.tsx
  client/src/components/aside/AsideButton.tsx
  client/src/components/aside/AsideLogo.tsx
  client/src/components/aside/AsideProfileBox.tsx
  client/src/constants/svg.tsx
  client/src/styles/GlobalStyles.tsx
Labels: 🐱 FE, 🖌️ UI

#157 [BE] JPA Auditing 활성화
  server/src/main/java/com/zerohip/server/ServerApplication.java
Labels: ✨ FEAT, 🐶 BE

#125 [FE] Custom Hooks : 거절 애니메이션, 에러 메시지 포함된 체크박스
  client/src/hooks/useCheckoutInput.tsx
  client/src/hooks/useComponents.tsx
  client/src/hooks/useRefusalAni.tsx
Labels: 🐱 FE, ✨ FEAT

#184 [FE] User 30 : 로그인 구현
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/image/imageUpload.svg
  client/public/image/logo.svg
  client/src/animation/404.json
  client/src/animation/500.json
  client/src/components/Aside.tsx
  client/src/components/CheckboxAgreement.tsx
  client/src/components/Loading.tsx
  client/src/components/SelectBox.tsx
  client/src/components/WithAuth.tsx
  client/src/components/redux/authnReducer.ts
  client/src/components/redux/hooks.ts
  client/src/components/redux/provider.tsx
  client/src/components/redux/store.ts
  client/src/components/redux/toast.ts
  client/src/constants/user.ts
  client/src/constants/userData.ts
  client/src/hooks/useCheckoutError.tsx
  client/src/pages/_app.tsx
  client/src/pages/api/user/login/index.ts
  client/src/pages/api/user/signup/index.ts
  client/src/pages/user/delete/goodbye/index.tsx
  client/src/pages/user/delete/index.tsx
  client/src/pages/user/login/index.tsx
  client/src/pages/user/mypage/[slug]/FollowList.tsx
  client/src/pages/user/mypage/[slug]/FollowModal.tsx
  client/src/pages/user/mypage/[slug]/index.tsx
  client/src/pages/user/signup/SignUpForm.tsx
  client/src/pages/user/signup/index.tsx
  client/src/pages/user/update/index.tsx
  client/src/services/apiUser.ts
  client/src/services/loginInstance.ts
  client/src/styles/GlobalStyles.tsx
  client/src/types/user.ts
  client/src/utils/validationCheck.ts
Labels: 🐱 FE, ✨ FEAT

#187 [FE] faRecUI-20 가계부 페이지 UI 작성
  client/next.config.js
  client/public/data/recordData.json
  client/public/images/icon/img.svg
  client/src/components/InputField.tsx
  client/src/components/Tab.tsx
  client/src/pages/api/financial-record/[slug]/index.ts
  client/src/pages/api/financial-record/index.ts
  client/src/pages/financial-record/FaRecForm.tsx
  client/src/pages/financial-record/ListItem.tsx
  client/src/pages/financial-record/financial-list/[slug]/RecordHeader.tsx
  client/src/pages/financial-record/financial-list/[slug]/index.tsx
  client/src/pages/financial-record/financial-list/[slug]/layout.tsx
  client/src/pages/financial-record/financial-list/[slug]/timeline.tsx
  client/src/pages/financial-record/index.tsx
  client/src/pages/financial-record/list/[slug]/FaRecArticle.tsx
  client/src/pages/financial-record/list/[slug]/FaRecCarousel.tsx
  client/src/pages/financial-record/list/[slug]/FaRecHeader.tsx
  client/src/pages/financial-record/list/[slug]/index.tsx
  client/src/pages/test/recordList.ts
  client/src/services/apiFinancial.ts
  client/src/styles/GlobalStyles.tsx
Labels: 🐱 FE, 🖌️ UI

#191 [FE] feat: 404 페이지 및 로딩 컴포넌트 생성
  client/package-lock.json
  client/package.json
  client/src/animation/404.json
  client/src/animation/loading.json
  client/src/components/Loading.tsx
  client/src/pages/404.tsx
Labels: 🐱 FE, ✨ FEAT

#185 [BE] 가계부 컨트롤러 추가 + 페이지네이션 기능
  server/src/main/java/com/zerohip/server/ServerApplication.java
  server/src/main/java/com/zerohip/server/common/page/dto/MultiResponseDto.java
  server/src/main/java/com/zerohip/server/common/page/dto/PageInfo.java
  server/src/main/java/com/zerohip/server/financialRecord/controller/FinancialRecordController.java
  server/src/main/java/com/zerohip/server/financialRecord/dto/FinancialRecordDto.java
  server/src/main/java/com/zerohip/server/financialRecord/entity/FinancialRecord.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordService.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordServiceImpl.java
  server/src/test/java/com/zerohip/server/financialRecord/service/FinancialRecordServiceImplTest.java
Labels: ✨ FEAT, 🐶 BE

#210 [BE]피드 게시글
  server/src/main/java/com/zerohip/server/common/feedType/FeedType.java
  server/src/main/java/com/zerohip/server/feedArticle/controller/FeedArticleController.java
  server/src/main/java/com/zerohip/server/feedArticle/entity/FeedArticle.java
  server/src/main/java/com/zerohip/server/feedArticle/mapper/FeedArticleMapper.java
  server/src/main/java/com/zerohip/server/feedArticle/repository/FeedArticleRepository.java
Labels: 🐛 FIX, ✨ FEAT, 🐶 BE

#211 [FE] User 175 : 회원 탈퇴 및 탈퇴 완료 페이지 구현
  client/package-lock.json
  client/package.json
  client/src/components/CheckboxAgreement.tsx
  client/src/components/Toast.tsx
  client/src/constants/user.ts
  client/src/hooks/useCheckoutError.tsx
  client/src/hooks/useCheckoutInput.tsx
  client/src/pages/404.tsx
  client/src/pages/_app.tsx
  client/src/pages/api/user/delete/index.ts
  client/src/pages/api/user/login/index.ts
  client/src/pages/user/delete/goodbye/index.tsx
  client/src/pages/user/delete/index.tsx
  client/src/pages/user/login/Google.tsx
  client/src/pages/user/login/Kakao.tsx
  client/src/pages/user/login/Naver.tsx
  client/src/pages/user/login/OAuth.tsx
  client/src/pages/user/login/index.tsx
  client/src/pages/user/signup/SignUpForm.tsx
  client/src/pages/user/signup/index.tsx
  client/src/pages/user/update/index.tsx
  client/src/services/apiUser.ts
Labels: 🐱 FE, ✨ FEAT

#212 [FE] !HOTFIX: props 에러 버그 수정
  client/src/components/Aside.tsx
  client/src/components/HomeHeader.tsx
  client/src/components/aside/AsideLogo.tsx
  client/src/components/aside/AsideProfileBox.tsx
  client/src/constants/svg.tsx
  client/src/pages/editor/index.tsx
  client/src/pages/index.tsx
Labels: 🐛 FIX, 🐱 FE, 🖌️ UI

#215 [FE] Common 214 : 재활용 가능한 만능 셀렉트 박스
  client/src/components/SelectBox.tsx
  client/src/constants/selectItems.ts
  client/src/pages/user/signup/SignUpForm.tsx
Labels: 🐱 FE, ✨ FEAT

#216 [FE] Commonization-188: 컴포넌트/함수 독립
  client/src/components/ImgsCarousel.tsx
  client/src/components/SnsArticle.tsx
  client/src/components/sns-article/ArticleHeader.tsx
  client/src/pages/index.tsx
  client/src/services/apiUser.ts
  client/src/utils/convertToKoreanDate.ts
  client/src/utils/numToStrWithSign.ts
Labels: 🐛 FIX, 🐱 FE, 🧹 CHORE

#220 [FE] BtnAndcategory-217 : button active, category 상수화
  client/src/constants/category.ts
  client/src/styles/CommonStyles.tsx
Labels: 🐛 FIX, 🐱 FE, ✨ FEAT, 🖌️ UI

#218 [BE] application-prod.yml 셋팅
  server/src/main/java/com/zerohip/server/common/img/dto/ImgDto.java
  server/src/main/java/com/zerohip/server/common/img/entity/Img.java
  server/src/main/java/com/zerohip/server/common/img/repository/ImgRepository.java
  server/src/main/java/com/zerohip/server/common/img/service/ImgService.java
  server/src/main/java/com/zerohip/server/common/img/service/ImgServiceImpl.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/entity/FinancialRecordArticle.java
  server/src/main/resources/application-prod.yml
Labels: ✨ FEAT, 🐶 BE

#223 Jwt security 176/refactoring reissu token logout
  server/src/main/java/com/zerohip/server/security/auth/AuthController.java
  server/src/main/java/com/zerohip/server/security/auth/AuthService.java
  server/src/main/java/com/zerohip/server/security/auth/controller/AuthController.java
  server/src/main/java/com/zerohip/server/security/auth/entity/RefreshToken.java
  server/src/main/java/com/zerohip/server/security/auth/repository/RefreshTokenRepository.java
  server/src/main/java/com/zerohip/server/security/auth/serivce/AuthService.java
  server/src/main/java/com/zerohip/server/security/config/SecurityConfig.java
  server/src/main/java/com/zerohip/server/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/zerohip/server/security/handler/UserAuthenticationEntryPoint.java
  server/src/main/java/com/zerohip/server/security/handler/UserAuthenticationFailureHandler.java
  server/src/main/java/com/zerohip/server/security/provider/JwtStatus.java
  server/src/main/java/com/zerohip/server/security/provider/JwtTokenizer.java
  server/src/main/java/com/zerohip/server/security/response/ErrorResponder.java
  server/src/main/java/com/zerohip/server/user/entity/User.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-prod.yml
Labels: ✨ FEAT, 🐶 BE

#225 [FE] Hamburger-213: 햄버거 버튼 구현
  client/src/components/aside/AsideButton.tsx
  client/src/components/aside/AsideHamburgerBtn.tsx
  client/src/components/aside/AsideLogo.tsx
  client/src/components/aside/AsideProfileBox.tsx
  client/src/constants/svg.tsx
Labels: 🐱 FE, 🖌️ UI

#227 [FE] carousel-swiper: Swiper.js 라이브러리로 이미지 캐러셀 개선
  client/package-lock.json
  client/package.json
  client/src/components/ImgsCarousel.tsx
  client/src/components/SnsArticle.tsx
  client/src/styles/GlobalStyles.tsx
Labels: 🐛 FIX, 🐱 FE, ✨ FEAT, 🖌️ UI

#228 [FE] User 172 : 코드리뷰 바탕으로 전면 리팩토링 및 마이페이지 구현
  client/next.config.js
  client/public/images/icon/hide.svg
  client/public/images/icon/show.svg
  client/src/components/BackBtn.tsx
  client/src/components/SelectBox.tsx
  client/src/components/SnsArticle.tsx
  client/src/components/Toast.tsx
  client/src/components/WithAuth.tsx
  client/src/components/aside/AsideProfileBox.tsx
  client/src/components/sns-article/ArticleHeader.tsx
  client/src/constants/userData.ts
  client/src/hooks/useCheckoutError.tsx
  client/src/hooks/useComponents.tsx
  client/src/pages/api/user/mypage/index.ts
  client/src/pages/financial-record/FaRecForm.tsx
  client/src/pages/financial-record/index.tsx
  client/src/pages/user/delete/goodbye/index.tsx
  client/src/pages/user/delete/index.tsx
  client/src/pages/user/login/Naver.tsx
  client/src/pages/user/login/index.tsx
  client/src/pages/user/mypage/FollowList.tsx
  client/src/pages/user/mypage/FollowModal.tsx
  client/src/pages/user/mypage/[slug]/FollowList.tsx
  client/src/pages/user/mypage/index.tsx
  client/src/pages/user/signup/PolicyAgreement.tsx
  client/src/pages/user/signup/SignUpForm.tsx
  client/src/pages/user/update/index.tsx
  client/src/services/apiUser.ts
  client/src/styles/GlobalStyles.tsx
  client/src/types/feed.ts
  client/src/types/user.ts
  client/src/utils/inputValidationError.ts
Labels: 🐱 FE, ✨ FEAT

#230 [FE] Overall-108: style: 명세서에 맞게 타입 수정 및 적용
  client/src/components/ImgsCarousel.tsx
  client/src/components/SnsArticle.tsx
  client/src/components/sns-article/ArticleHeader.tsx
  client/src/pages/editor/index.tsx
  client/src/pages/index.tsx
  client/src/pages/user/mypage/index.tsx
  client/src/types/article.ts
  client/src/types/feed.ts
  client/tsconfig.json
Labels: 🐛 FIX, 🐱 FE, 🖌️ UI

#233 [FE] faRecFeat-18 가계부 페이지 기능
  client/package-lock.json
  client/package.json
  client/public/data/recordData.json
  client/public/data/recordHeader.json
  client/public/images/icon/bookmark.svg
  client/public/images/icon/img.svg
  client/public/images/icon/person.svg
  client/public/images/icon/plus.svg
  client/public/images/icon/search.svg
  client/src/components/Category.tsx
  client/src/components/FilePlusLabel.tsx
  client/src/components/Pagination.tsx
  client/src/components/SnsArticle.tsx
  client/src/constants/svg.tsx
  client/src/pages/api/financial-record/[slug]/article/index.ts
  client/src/pages/financial-record/FaRecForm.tsx
  client/src/pages/financial-record/ListItem.tsx
  client/src/pages/financial-record/edit/[slug]/index.tsx
  client/src/pages/financial-record/index.tsx
  client/src/pages/financial-record/list/[slug]/FaRecArticle.tsx
  client/src/pages/financial-record/list/[slug]/FaRecCarousel.tsx
  client/src/pages/financial-record/list/[slug]/FaRecHeader.tsx
  client/src/pages/financial-record/list/[slug]/index.tsx
  client/src/pages/index.tsx
  client/src/pages/test/recordArticle.ts
  client/src/services/apiFinancial.ts
  client/src/styles/CommonStyles.tsx
  client/src/types/financialRecord.ts
  client/src/utils/convertToKoreanDate.ts
Labels: 🐱 FE, ✨ FEAT, 🖌️ UI

#229 [FE] USER-234 : 로그아웃 및 new access 토큰 요청
  client/public/images/icon/back2.svg
  client/public/images/icon/closeBtn.svg
  client/public/images/icon/dropdown.svg
  client/public/images/icon/google.svg
  client/public/images/icon/imageUpload.svg
  client/public/images/icon/kakao.svg
  client/public/images/icon/naver.svg
  client/public/images/logo.svg
  client/src/components/BackBtn.tsx
  client/src/components/SelectBox.tsx
  client/src/components/WithAuth.tsx
  client/src/components/aside/AsideHamburgerBtn.tsx
  client/src/constants/user.ts
  client/src/hooks/useLogout.ts
  client/src/pages/api/user/login/index.ts
  client/src/pages/api/user/mypage/index.ts
  client/src/pages/api/user/update/index.ts
  client/src/pages/user/delete/goodbye/index.tsx
  client/src/pages/user/delete/index.tsx
  client/src/pages/user/login/Google.tsx
  client/src/pages/user/login/Kakao.tsx
  client/src/pages/user/login/Naver.tsx
  client/src/pages/user/login/index.tsx
  client/src/pages/user/mypage/FollowModal.tsx
  client/src/pages/user/mypage/index.tsx
  client/src/pages/user/signup/SignUpForm.tsx
  client/src/pages/user/signup/index.tsx
  client/src/pages/user/update/index.tsx
  client/src/services/apiUser.ts
  client/src/types/user.ts
Labels: 🐱 FE, ✨ FEAT

#237 [BE] Init: 가계부, 게시글 MockupData 추가
  server/src/main/java/com/zerohip/server/MockDataInit.java
Labels: 🔥 INIT, 🐶 BE

#238 [BE] 목업데이터 머지
  server/src/main/java/com/zerohip/server/MockDataInit.java
Labels: 🔥 INIT, 🐶 BE

#239 [BE] Financial record article faDate Date to LocalDate
  server/src/main/java/com/zerohip/server/financialRecordArticle/dto/FinancialRecordArticleDto.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/entity/FinancialRecordArticle.java
Labels: 🐛 FIX, 🐶 BE

#241 [BE] Test be to dev with Date to LocalDate faRec
  server/src/main/java/com/zerohip/server/financialRecordArticle/dto/FinancialRecordArticleDto.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/entity/FinancialRecordArticle.java
Labels: 🐛 FIX, 🐶 BE

#244 [BE] Article Interface to Abstract Class
  server/src/main/java/com/zerohip/server/common/article/Article.java
  server/src/main/java/com/zerohip/server/common/comment/dto/CommentDto.java
  server/src/main/java/com/zerohip/server/common/comment/entity/Comment.java
  server/src/main/java/com/zerohip/server/common/comment/repository/CommentRepository.java
  server/src/main/java/com/zerohip/server/common/comment/service/CommentService.java
  server/src/main/java/com/zerohip/server/common/comment/service/CommentServiceImpl.java
  server/src/main/java/com/zerohip/server/feedArticle/entity/FeedArticle.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/entity/FinancialRecordArticle.java
Labels: 🐛 FIX, 🐶 BE

#246 [BE] fix: id to articleId
  server/src/main/java/com/zerohip/server/common/article/Article.java
  server/src/main/java/com/zerohip/server/feedArticle/entity/FeedArticle.java
Labels: 🐛 FIX, 🐶 BE

#247 [FE] Refac-245 에러 처리 관련 리팩토링 및 css 반응형 처리
  client/src/components/ErrorComponent.tsx
  client/src/components/Pagination.tsx
  client/src/pages/api/financial-record/[slug]/article/index.ts
  client/src/pages/financial-record/FaRecForm.tsx
  client/src/pages/financial-record/index.tsx
  client/src/pages/financial-record/list/[slug]/FaRecArticle.tsx
  client/src/pages/financial-record/list/[slug]/FaRecHeader.tsx
  client/src/pages/financial-record/list/[slug]/index.tsx
  client/src/pages/test/recordArticle.ts
  client/src/services/apiFinancial.ts
  client/src/styles/CommonStyles.tsx
  client/src/styles/GlobalStyles.tsx
  server/gradlew
Labels: 🐱 FE, ✨ FEAT, 🖌️ UI

#248 [FE] User 172 : 회원 정보 페이지의 이미지 수정 기능 구현
  client/public/image/mango.png
  client/public/image/mango2.png
  client/src/components/BackBtn.tsx
  client/src/components/WithAuth.tsx
  client/src/components/img-crop/ImgCropModal.tsx
  client/src/components/redux/currentImgReducer.ts
  client/src/components/redux/store.ts
  client/src/pages/api/user/mypage/index.ts
  client/src/pages/user/mypage/index.tsx
  client/src/pages/user/update/InputField.tsx
  client/src/pages/user/update/ProfileImgUpdate.tsx
  client/src/pages/user/update/RandomAvatarUpdate.tsx
  client/src/pages/user/update/UserImgFileUpdate.tsx
  client/src/pages/user/update/UserUpdatePage.tsx
  client/src/pages/user/update/index.tsx
  client/src/services/apiUser.ts
  client/src/services/loginInstance.ts
  client/src/types/user.ts
  client/src/utils/extractFromURL.ts
Labels: 🐱 FE, ✨ FEAT

#249 [BE] Financial record article - 인가된 유저 확인 코드 추가
  server/src/main/java/com/zerohip/server/common/img/dto/ImgDto.java
  server/src/main/java/com/zerohip/server/common/img/entity/Img.java
  server/src/main/java/com/zerohip/server/common/img/repository/ImgRepository.java
  server/src/main/java/com/zerohip/server/common/img/service/ImgService.java
  server/src/main/java/com/zerohip/server/common/img/service/ImgServiceImpl.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/controller/FinancialRecordArticleController.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/dto/FinancialRecordArticleDto.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/entity/FinancialRecordArticle.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleService.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleServiceImpl.java
  server/src/main/java/com/zerohip/server/user/entity/User.java
  server/src/test/java/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleServiceImplTest.java
Labels: ✨ FEAT, 🐶 BE

#252 [BE] Financial record article 생성자 수정
  server/src/main/java/com/zerohip/server/MockDataInit.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/entity/FinancialRecordArticle.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleServiceImpl.java
Labels: 🐛 FIX, 🐶 BE

#251 [BE] 인가된 유저 정보 추가 및 게시글&타임라인 count 추가
  server/src/main/java/com/zerohip/server/financialRecord/controller/FinancialRecordController.java
  server/src/main/java/com/zerohip/server/financialRecord/dto/FinancialRecordDto.java
  server/src/main/java/com/zerohip/server/financialRecord/entity/FinancialRecord.java
  server/src/main/java/com/zerohip/server/financialRecord/repository/FinancialRecordRepository.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordService.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordServiceImpl.java
  server/src/test/java/com/zerohip/server/financialRecord/service/FinancialRecordServiceImplTest.java
Labels: ✨ FEAT, 🐶 BE

#254 [BE] 가계부/가계부게시글 - 인가된 사용자 로직 수정
  server/.gitignore
  server/src/main/java/com/zerohip/server/common/page/dto/MultiResponseDto.java
  server/src/main/java/com/zerohip/server/financialRecord/dto/FinancialRecordDto.java
  server/src/main/java/com/zerohip/server/financialRecord/entity/FinancialRecord.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordService.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordServiceImpl.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/controller/FinancialRecordArticleController.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/dto/FinancialRecordArticleDto.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/entity/FinancialRecordArticle.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/mapper/FinancialRecordArticleMapper.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleService.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleServiceImpl.java
Labels: 🐛 FIX, ✨ FEAT, 🐶 BE

#256 [FE] Refac 코드 리팩토링 작업
  client/public/data/recordHeader.json
  client/src/constants/faRec.ts
  client/src/constants/pageNames.ts
  client/src/pages/financial-record/FaRecForm.tsx
  client/src/pages/financial-record/create/index.tsx
  client/src/pages/financial-record/edit/[slug]/index.tsx
  client/src/pages/financial-record/index.tsx
  client/src/pages/financial-record/list/[slug]/FaRecHeader.tsx
  client/src/pages/financial-record/list/[slug]/index.tsx
  client/src/types/article.ts
  client/src/types/financialRecord.ts
Labels: 🐛 FIX, 🐱 FE

#258 [BE] Fix authentication 257/be
  server/build.gradle
  server/src/main/java/com/zerohip/server/security/auth/controller/AuthController.java
  server/src/main/java/com/zerohip/server/security/auth/serivce/AuthService.java
  server/src/main/java/com/zerohip/server/security/config/SecurityConfig.java
  server/src/main/java/com/zerohip/server/security/config/SecurityCorsConfig.java
  server/src/main/java/com/zerohip/server/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/zerohip/server/security/handler/UserAuthenticationEntryPoint.java
  server/src/main/java/com/zerohip/server/security/response/ErrorResponder.java
  server/src/main/java/com/zerohip/server/user/controller/UserController.java
  server/src/main/java/com/zerohip/server/user/entity/User.java
  server/src/main/java/com/zerohip/server/user/service/UserService.java
  server/src/main/java/com/zerohip/server/user/service/UserServiceImpl.java
  server/src/main/resources/application-local.yml
Labels: 🐛 FIX, 🐶 BE

#259 [BE] 피드게시글 scope 값 추가 및 user 매핑
  server/src/main/java/com/zerohip/server/common/feedType/FeedType.java
  server/src/main/java/com/zerohip/server/feedArticle/controller/FeedArticleController.java
  server/src/main/java/com/zerohip/server/feedArticle/dto/FeedArticleDto.java
  server/src/main/java/com/zerohip/server/feedArticle/entity/FeedArticle.java
  server/src/main/java/com/zerohip/server/feedArticle/mapper/FeedArticleMapper.java
  server/src/main/java/com/zerohip/server/feedArticle/service/FeedArticleService.java
  server/src/main/java/com/zerohip/server/feedArticle/service/FeedArticleServiceImpl.java
Labels: 🐛 FIX, ✨ FEAT, 🐶 BE

#260 [FE] User 250 : 로그인 검증 HOC 함수 및 instance 완성 외 리팩토링
  client/src/components/WithAuth.tsx
  client/src/components/aside/AsideHamburgerBtn.tsx
  client/src/hooks/useLogout.ts
  client/src/pages/api/user/logout/index.ts
  client/src/pages/user/delete/index.tsx
  client/src/pages/user/login/index.tsx
  client/src/pages/user/mypage/index.tsx
  client/src/pages/user/signup/SignUpForm.tsx
  client/src/pages/user/signup/SignUpInputField.tsx
  client/src/pages/user/update/UserInputField.tsx
  client/src/pages/user/update/UserUpdatePage.tsx
  client/src/services/apiUser.ts
  client/src/services/tokenInstance.ts
  client/src/services/useMutateUser.ts
  client/src/types/user.ts
  client/src/utils/getAccessToken.tsx
Labels: 🐱 FE, ✨ FEAT

#261 [FE] Overall-232: 태블릿/모바일 반응형 구현 & 기타 코드 수정
  client/src/components/Aside.tsx
  client/src/components/HomeHeader.tsx
  client/src/components/ImgsCarousel.tsx
  client/src/components/SnsArticle.tsx
  client/src/components/aside/AsideBtn.tsx
  client/src/components/aside/AsideHamburgerBtn.tsx
  client/src/components/aside/AsideLogo.tsx
  client/src/components/aside/AsideProfileBox.tsx
  client/src/components/aside/MobileEditBtn.tsx
  client/src/components/home-header/MobileHomeHeaderLogo.tsx
  client/src/components/home-header/ProfileHamburgerBtn.tsx
  client/src/components/img-crop/ImgCropModal.tsx
  client/src/components/sns-article/ArticleHeader.tsx
  client/src/components/sns-article/VoteForm.tsx
  client/src/constants/enums.ts
  client/src/constants/svg.tsx
  client/src/hooks/useWindowSize.ts
  client/src/pages/_app.tsx
  client/src/pages/editor/InputNaturalNumber.tsx
  client/src/pages/editor/index.tsx
  client/src/pages/index.tsx
  client/src/styles/GlobalStyles.tsx
Labels: 🐱 FE

#263 !HOTFIX: useLogout → useMutateUser 최신화
  client/src/components/home-header/ProfileHamburgerBtn.tsx
Labels: 🐛 FIX, 🐱 FE

#264 !HOTFIX: 모든 데스크탑/태블릿 화면에 margin-left가 적용되는 버그 수정
  client/src/pages/_app.tsx
Labels: 🐛 FIX, 🐱 FE, 🖌️ UI

#265 [FE] !HOTFIX: 화면 width 1024px 미만일 경우 font-size 14px로 통일
  client/src/styles/GlobalStyles.tsx
Labels: 🐛 FIX, 🐱 FE

#268 [BE]feat: articlId 생성
  server/src/main/java/com/zerohip/server/feedArticle/dto/FeedArticleDto.java
  server/src/main/java/com/zerohip/server/feedArticle/entity/FeedArticle.java
Labels: ✨ FEAT, 🐶 BE

#269 [FE] User 250 : 반응형 구현 및 웹 접근성을 위한 코드 리팩토링
  client/public/images/favicon.ico
  client/src/components/BackBtn.tsx
  client/src/components/WithAuth.tsx
  client/src/components/img-crop/ImgCropModal.tsx
  client/src/hooks/useComponents.tsx
  client/src/pages/_document.tsx
  client/src/pages/user/delete/goodbye/index.tsx
  client/src/pages/user/delete/index.tsx
  client/src/pages/user/login/index.tsx
  client/src/pages/user/mypage/FollowList.tsx
  client/src/pages/user/mypage/FollowModal.tsx
  client/src/pages/user/mypage/index.tsx
  client/src/pages/user/signup/SignUpForm.tsx
  client/src/pages/user/signup/index.tsx
  client/src/pages/user/update/ProfileImgUpdate.tsx
  client/src/pages/user/update/ProfileImgUpdateModal.tsx
  client/src/pages/user/update/RandomAvatarUpdate.tsx
  client/src/pages/user/update/UserImgFileUpdate.tsx
  client/src/pages/user/update/UserInputField.tsx
  client/src/pages/user/update/UserUpdatePage.tsx
  client/src/services/apiUser.ts
  client/src/services/tokenInstance.ts
  client/src/styles/CommonStyles.tsx
  client/src/styles/GlobalStyles.tsx
Labels: 🐱 FE, 🖌️ UI

#271 [BE] 로그인 사용자 Info 기능 구현
  server/src/main/java/com/zerohip/server/user/controller/UserController.java
Labels: ✨ FEAT, 🐶 BE

#277 [FE] User 275 : 개인정보 처리약관 추가 및 README 일부 완성
  README.md
  client/src/constants/messages/user.ts
  client/src/pages/user/signup/PersonalInfoLaw.tsx
  client/src/pages/user/signup/PolicyAgreement.tsx
  client/src/pages/user/signup/SignUpForm.tsx
  client/src/pages/user/update/UserUpdatePage.tsx
  client/src/utils/inputValidationError.ts
Labels: 🐱 FE, 🧹 CHORE

#279 [FE] User 275 : 메타데이터, OG 설정 컴포넌트로 SEO 개선
  client/public/images/image/zerohipOGImg.png
  client/src/components/HeadMeta.tsx
  client/src/constants/seo/userMetaData.ts
  client/src/hooks/useComponents.tsx
  client/src/pages/_document.tsx
  client/src/pages/user/delete/goodbye/index.tsx
  client/src/pages/user/delete/index.tsx
  client/src/pages/user/login/index.tsx
  client/src/pages/user/mypage/FollowModal.tsx
  client/src/pages/user/mypage/index.tsx
  client/src/pages/user/signup/PolicyAgreement.tsx
  client/src/pages/user/signup/index.tsx
  client/src/pages/user/update/index.tsx
  client/src/services/apiUser.ts
Labels: 🐱 FE, 🧹 CHORE

#280 [FE] Img: 이미지 원본 보기 기능 구현 (공동 작업)
  client/package-lock.json
  client/package.json
  client/src/components/ImgsCarousel.tsx
  client/src/components/SnsArticle.tsx
  client/src/constants/svg.tsx
  client/src/services/apiFinancial.ts
Labels: 🐱 FE, ✨ FEAT, 🖌️ UI

#278 [BE] Common img upload
  server/build.gradle
  server/src/main/java/com/zerohip/server/aws/config/S3Config.java
  server/src/main/java/com/zerohip/server/aws/config/S3ServiceImpl.java
  server/src/main/java/com/zerohip/server/common/img/dto/ImgDto.java
  server/src/main/java/com/zerohip/server/common/img/entity/Img.java
  server/src/main/java/com/zerohip/server/common/img/repository/ImgRepository.java
  server/src/main/java/com/zerohip/server/common/img/service/ImgService.java
  server/src/main/java/com/zerohip/server/common/img/service/ImgServiceImpl.java
  server/src/main/java/com/zerohip/server/common/img/service/S3ImgServiceImpl.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/controller/FinancialRecordArticleController.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/dto/FinancialRecordArticleDto.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/entity/FinancialRecordArticle.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/mapper/FinancialRecordArticleMapper.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleService.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleServiceImpl.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-prod.yml
Labels: ✨ FEAT, 🐶 BE

#284 [BE] OAuth2 로그인 인증 구현
  server/src/main/java/com/zerohip/server/security/auth/controller/AuthController.java
  server/src/main/java/com/zerohip/server/security/auth/serivce/AuthService.java
  server/src/main/java/com/zerohip/server/security/config/PasswordEncoderConfig.java
  server/src/main/java/com/zerohip/server/security/config/SecurityConfig.java
  server/src/main/java/com/zerohip/server/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/zerohip/server/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/zerohip/server/security/handler/UserAuthenticationFailureHandler.java
  server/src/main/java/com/zerohip/server/security/oauth2/handler/OAuth2UserSuccessHandler.java
  server/src/main/java/com/zerohip/server/security/oauth2/provider/OAuth2Attribute.java
  server/src/main/java/com/zerohip/server/security/oauth2/service/CustomOAuth2UserService.java
  server/src/main/java/com/zerohip/server/security/provider/JwtTokenizer.java
  server/src/main/java/com/zerohip/server/user/dto/UserDto.java
  server/src/main/java/com/zerohip/server/user/entity/User.java
  server/src/main/java/com/zerohip/server/user/service/UserService.java
  server/src/main/java/com/zerohip/server/user/service/UserServiceImpl.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-prod.yml
Labels: ✨ FEAT, 🐶 BE

#272 [BE] Comment 테이블 생성되지 않던 에러 해결
  server/src/main/java/com/zerohip/server/common/comment/dto/CommentDto.java
  server/src/main/java/com/zerohip/server/common/comment/entity/Comment.java
Labels: 🐛 FIX, 🐶 BE

#287 [BE] Common img upload - faRec
  server/src/main/java/com/zerohip/server/aws/config/S3ServiceImpl.java
  server/src/main/java/com/zerohip/server/common/img/dto/ImgDto.java
  server/src/main/java/com/zerohip/server/common/img/entity/Img.java
  server/src/main/java/com/zerohip/server/common/img/service/ImgService.java
  server/src/main/java/com/zerohip/server/common/img/service/ImgServiceImpl.java
  server/src/main/java/com/zerohip/server/common/img/service/S3ImgServiceImpl.java
  server/src/main/java/com/zerohip/server/financialRecord/controller/FinancialRecordController.java
  server/src/main/java/com/zerohip/server/financialRecord/dto/FinancialRecordDto.java
  server/src/main/java/com/zerohip/server/financialRecord/entity/FinancialRecord.java
  server/src/main/java/com/zerohip/server/financialRecord/mapper/FinancialRecordMapper.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordService.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordServiceImpl.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/controller/FinancialRecordArticleController.java
Labels: ✨ FEAT, 🐶 BE

#289 [BE] Financial rec 사용자 인증방식 변경
  server/src/main/java/com/zerohip/server/financialRecord/controller/FinancialRecordController.java
  server/src/main/java/com/zerohip/server/financialRecord/repository/FinancialRecordRepository.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordService.java
  server/src/main/java/com/zerohip/server/financialRecord/service/FinancialRecordServiceImpl.java
Labels: 🐛 FIX, 🐶 BE

#290 [BE] fix: 사용자 인증 User to String authorId
  server/src/main/java/com/zerohip/server/financialRecordArticle/controller/FinancialRecordArticleController.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleService.java
  server/src/main/java/com/zerohip/server/financialRecordArticle/service/FinancialRecordArticleServiceImpl.java
Labels: 🐛 FIX, 🐶 BE

#297 [FE] FaRec test
  client/public/data/recordHeader.json
  client/public/data/recordList.json
  client/src/pages/api/financial-record/[slug]/article/index.ts
  client/src/pages/financial-record/FaRecForm.tsx
  client/src/pages/financial-record/ImgBox.tsx
  client/src/pages/financial-record/ListItem.tsx
  client/src/pages/financial-record/index.tsx
  client/src/pages/financial-record/list/[slug]/index.tsx
  client/src/pages/test/recordArticle.ts
  client/src/services/apiFinancial.ts
Labels: 🐱 FE, ✨ FEAT

#294 [BE] 회원 정보 수정 기능 구현 및 profileImgPath 추가
  server/src/main/java/com/zerohip/server/user/controller/UserController.java
  server/src/main/java/com/zerohip/server/user/dto/UserDto.java
  server/src/main/java/com/zerohip/server/user/entity/User.java
  server/src/main/java/com/zerohip/server/user/service/UserServiceImpl.java
  server/src/main/resources/application-local.yml
Labels: ✨ FEAT, 🐶 BE

#295 [BE] feat: feedArticle 회원 별 피드 기능 및 author->authorId
  server/src/main/java/com/zerohip/server/feedArticle/controller/FeedArticleController.java
  server/src/main/java/com/zerohip/server/feedArticle/repository/FeedArticleRepository.java
  server/src/main/java/com/zerohip/server/feedArticle/service/FeedArticleService.java
  server/src/main/java/com/zerohip/server/feedArticle/service/FeedArticleServiceImpl.java
Labels: ✨ FEAT, 🐶 BE

#298 [FE] faRecError error 처리 및 메타데이터 삽입
  client/src/constants/messages/faRec.ts
  client/src/constants/pageNames.ts
  client/src/constants/seo/faRecMetaData.ts
  client/src/pages/financial-record/FaRecForm.tsx
  client/src/pages/financial-record/create/index.tsx
  client/src/pages/financial-record/edit/[slug]/index.tsx
  client/src/pages/financial-record/index.tsx
  client/src/pages/financial-record/list/[slug]/index.tsx
  client/src/services/apiFinancial.ts
Labels: 🐱 FE, ✨ FEAT

#299 [FE] 마이페이지 무한스크롤 구현
  client/src/components/ErrorComponent.tsx
  client/src/components/WithAuth.tsx
  client/src/components/redux/authnReducer.ts
  client/src/components/redux/getUserInfo.tsx
  client/src/pages/api/user/[slug]/feedArticles/index.ts
  client/src/pages/api/user/mypage/index.ts
  client/src/pages/user/mypage/MyPageUserInfo.tsx
  client/src/pages/user/mypage/index.tsx
  client/src/services/apiUser.ts
  client/src/types/user.ts
  client/src/utils/getAccessToken.tsx
Labels: 🐱 FE, ✨ FEAT

#301 [FE] Proxy 추가
  client/next.config.js
  client/src/services/apiFinancial.ts
  client/src/services/apiUser.ts
Labels: 🐱 FE, ✨ FEAT

#291 [FE] http-editor: editor 페이지, `<SnsArticle>` 관련 HTTP 통신 코드 수정
  client/src/components/Aside.tsx
  client/src/components/HomeHeader.tsx
  client/src/components/SnsArticle.tsx
  client/src/components/sns-article/VoteForm.tsx
  client/src/constants/articleDummyData.ts
  client/src/pages/editor/ImgBox.tsx
  client/src/pages/editor/ImgsUploader.tsx
  client/src/pages/editor/SelectOption.tsx
  client/src/pages/editor/index.tsx
  client/src/pages/financial-record/edit/[slug]/index.tsx
  client/src/pages/financial-record/list/[slug]/FaRecHeader.tsx
  client/src/pages/financial-record/list/[slug]/index.tsx
  client/src/pages/index.tsx
  client/src/types/article.ts
Labels: 🐛 FIX, 🐱 FE, ✨ FEAT

#303 Readme
  README.md
Labels: 🧹 CHORE

#304 [FE] test : test용 reactquery 분리 axios 수정
  client/src/pages/financialrecord/FaRecForm.tsx
  client/src/pages/financialrecord/ImgBox.tsx
  client/src/pages/financialrecord/ListItem.tsx
  client/src/pages/financialrecord/create/index.tsx
  client/src/pages/financialrecord/edit/[slug]/index.tsx
  client/src/pages/financialrecord/index copy.tsx
  client/src/pages/financialrecord/index.tsx
  client/src/pages/financialrecord/list/[slug]/FaRecArticle.tsx
  client/src/pages/financialrecord/list/[slug]/FaRecHeader.tsx
  client/src/pages/financialrecord/list/[slug]/index.tsx
  client/src/services/apiFinancial.ts
Labels: 🐛 FIX, 🐱 FE

#305 [FE] !HOTFIX 재요청 횟수 제한하는 로직 추가
  client/src/components/Aside.tsx
  client/src/components/WithAuth.tsx
  client/src/components/aside/AsideProfileBox.tsx
  client/src/components/redux/getUserInfo.tsx
  client/src/pages/_app.tsx
  client/src/pages/api/user/login/index.ts
  client/src/pages/api/user/signup/index.ts
  client/src/pages/user/mypage/index.tsx
  client/src/services/tokenInstance.ts
Labels: 🐛 FIX, 🐱 FE, ✨ FEAT

#306 [FE] Aside-isloggedout: 로그아웃 상태에서 헤더에 로그인 버튼(사람 아이콘) 추가
  client/src/components/Aside.tsx
  client/src/components/HomeHeader.tsx
  client/src/components/home-header/MobileLoginBtn.tsx
Labels: 🐛 FIX, 🐱 FE, 🖌️ UI

#309 [FE] Aside-isloggedout: WithAuth 테스트 중
  client/src/components/Aside.tsx
  client/src/components/SnsArticle.tsx
  client/src/components/aside/AsideHamburgerBtn.tsx
  client/src/components/home-header/ProfileHamburgerBtn.tsx
  client/src/pages/_app.tsx
  client/src/pages/editor/index.tsx
Labels: 🐛 FIX, 🐱 FE, 🖌️ UI

#311 [BE] Login 시 userInfo 반환 - profileImgPath 추가
  server/src/main/java/com/zerohip/server/security/auth/NeverLandUserDetailsService.java
  server/src/main/java/com/zerohip/server/security/handler/UserAuthenticationSuccessHandler.java
  server/src/main/resources/application-local.yml
Labels: 🐛 FIX, 🐶 BE

#312 [FE] article-U-300: 수정/삭제 버튼에 기능 추가
  client/src/components/SnsArticle.tsx
Labels: 🐱 FE, ✨ FEAT

#315 [FE] !HOTFIX: 무한 스크롤 관련 코드 undefined 에러 수정
  client/src/components/SnsArticle.tsx
  client/src/pages/index.tsx
Labels: 🐛 FIX, 🐱 FE

#314 [FE] 회원 정보 수정 기능 일부 수정
  client/src/components/WithAuth.tsx
  client/src/pages/oauth/google/index.tsx
  client/src/pages/oauth/kakao/index.tsx
  client/src/pages/oauth/naver/index.tsx
  client/src/pages/user/update/UserUpdatePage.tsx
  client/src/services/apiUser.ts
  client/src/services/useMutateUser.ts
  client/src/types/user.ts
Labels: 🐛 FIX, 🐱 FE, 🧹 CHORE

#316 [FE] !HOTFIX: convertToKoreanDate & convertToKoreanMonthDay에 useEffect 적용
  client/src/components/sns-article/ArticleHeader.tsx
  client/src/pages/financialrecord/list/[slug]/FaRecArticle.tsx
Labels: 🐛 FIX, 🐱 FE

#318 [FE] hotfix-login-signup: 회원가입/로그인 input 버그 수정
  client/src/hooks/useComponents.tsx
  client/src/utils/validationCheck.ts
Labels: 🐛 FIX, 🐱 FE

#322 [FE] About 상수 변경
  client/public/images/image/aboutProfile/sunbbang0.jpg
  client/public/images/image/aboutProfile/sunbbang1.jpg
  client/public/images/image/aboutProfile/sunbbang2.jpg
  client/public/images/image/aboutProfile/sunbbang3.jpg
  client/public/images/image/aboutProfile/sunbbang4.jpeg
  client/public/images/image/aboutProfile/sunbbang5.jpg
  client/src/constants/about.ts
  client/src/styles/AboutStyles.tsx
Labels: 📄 DOCS, 🐱 FE
